export const videoCard = [
   {
     key: 1,
     thumbnail: '/thumbnails/started.jpeg', 
     channelPicture: '/thumbnails/channelPicture.jpg', 
     channelName: 'Chulo Cr8v', 
     title: 'How to get started', 
     views: 69055600,
     likes: '10k', 
     timeStamp: '1 day ago', 
     followers: '100,000', 
     videoSummary: 'Lorem ipsum dolor sit amet elit. Phasellus nec pretium mi. Curabitur facilisis ornare velit non. You can always ask for more information about your privacy policy and. Lorem ipsum dolor sit amet elit. Phasellus nec pretium mi. '
   }, 
   {
     key: 2,
     thumbnail: '/thumbnails/cities.jpg', 
     channelPicture: '/thumbnails/channelPicture.jpg', 
     channelName: 'Chulo Cr8v', 
     title: 'Top 10 cities to avoid today 😱 🤯', 
     views: 10500,
     likes: '1M', 
     timeStamp: '2 days ago',
     followers: '100,000', 
     videoSummary: 'Lorem ipsum dolor sit amet elit. Phasellus nec pretium mi. Curabitur facilisis ornare velit non. You can always ask for more information about your privacy policy and. Lorem ipsum dolor sit amet elit. Phasellus nec pretium mi. ', 
   }, 
   {
     key: 3,
     thumbnail: '/thumbnails/code.jpg', 
     channelPicture: '/thumbnails/channelPicture.jpg', 
     channelName: 'Chulo Cr8v', 
     title: 'Make coding easier with these simple tricks 🤯', 
     views: 95400,
     likes: '94k', 
     timeStamp: '3 days ago', 
     followers: '100,000', 
     videoSummary: 'Lorem ipsum dolor sit amet elit. Phasellus nec pretium mi. Curabitur facilisis ornare velit non. You can always ask for more information about your privacy policy and. Lorem ipsum dolor sit amet elit. Phasellus nec pretium mi. ',
   }, 
   {
     key: 4,
     thumbnail: '/thumbnails/productive.jpg', 
     channelPicture: '/thumbnails/channelPicture.jpg', 
     channelName: 'Chulo Cr8v', 
     title: 'Boost your productivity with these simple tricks', 
     views: 195400,
     likes: '100k', 
     timeStamp: '4 days ago', 
     followers: '100,000', 
     videoSummary: 'Lorem ipsum dolor sit amet elit. Phasellus nec pretium mi. Curabitur facilisis ornare velit non. You can always ask for more information about your privacy policy and. Lorem ipsum dolor sit amet elit. Phasellus nec pretium mi. ', 
   }, 
]