export const SampleComments = [{
  commentId: 1,
  postId: 1,
  comment: 'Lorem ipsum dolor sit amet elit. Phasellus nec pretium mi. Curabitur facilisis.',
  commenter: 'Volks Shane',
  commenterPicture: '/thumbnails/pp.jpg',
  timeStamp: '1 day ago',
},
  {
    commentId: 2,
    postId: 2,
    comment: 'Lorem ipsum dolor sit amet elit. Phasellus nec pretium mi. Curabitur facilisis.',
    commenter: 'Mitch Wagen',
    commenterPicture: '/thumbnails/pp1.jpg',
    timeStamp: '2 days ago',
  },
  {
    commentId: 3,
    postId: 3,
    comment: 'Lorem ipsum dolor sit amet elit. Phasellus nec pretium mi. Curabitur facilisis.',
    commenter: 'Toyo Ta',
    commenterPicture: '/thumbnails/pp2.jpg',
    timeStamp: '2 days ago',
  },
  {
    commentId: 4,
    postId: 4,
    comment: 'Lorem ipsum dolor sit amet elit. Phasellus nec pretium mi. Curabitur facilisis.',
    commenter: 'Merc Edis',
    commenterPicture: '',
    timeStamp: '3 days ago',
  },
  {
    commentId: 5,
    postId: 1,
    comment: 'Lorem ipsum dolor sit amet elit. Phasellus nec pretium mi. Curabitur facilisis.',
    commenter: 'Merc Edis',
    commenterPicture: '',
    timeStamp: '3 days ago',
  },
  {
    commentId: 6,
    postId: 2,
    comment: 'Lorem ipsum dolor sit amet elit. Phasellus nec pretium mi. Curabitur facilisis.',
    commenter: 'Merc Edis',
    commenterPicture: '',
    timeStamp: '3 days ago',
  },
  {
    commentId: 7,
    postId: 4,
    comment: 'Lorem ipsum dolor sit amet elit. Phasellus nec pretium mi. Curabitur facilisis.',
    commenter: 'Merc Edis',
    commenterPicture: '',
    timeStamp: '3 days ago',
  }]